/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.event;

/**
 *
 * @author bapti
 */
public class CheckBoxTambahan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckBoxTambahan.class.getName());

    /**
     * Creates new form CheckBoxTambahan
     */
    public CheckBoxTambahan() {
        initComponents();
    }
    
    private String formatRupiah(int nominal){
        return "Rp." + String.format(java.util.Locale.forLanguageTag("id-ID"), "%,d", nominal);
    }
    
    private void hitungTotal(){
        int total = 25000;
        
        if(cbxGulaAren.isSelected()){
            total += 3000;
        }
        if(cbxSusuOat.isSelected()){
            total += 5000;
        }
        if(cbxExtraShot.isSelected()){
            total += 4000;
        }
        
        lblTotalHarga.setText(formatRupiah(total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHargaLatte = new javax.swing.JLabel();
        lblTambahan = new javax.swing.JLabel();
        cbxGulaAren = new javax.swing.JCheckBox();
        cbxSusuOat = new javax.swing.JCheckBox();
        cbxExtraShot = new javax.swing.JCheckBox();
        lblTotalHargaText = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tambahan Kopi");

        lblHargaLatte.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHargaLatte.setText("Latte - Rp25.000");

        lblTambahan.setText("Tambahan:");

        cbxGulaAren.setText("Gula Aren(+ Rp 3.000)");
        cbxGulaAren.addItemListener(this::cbxGulaArenItemStateChanged);
        cbxGulaAren.addActionListener(this::cbxGulaArenActionPerformed);

        cbxSusuOat.setText("Susu Oat(+ Rp 5.000)");
        cbxSusuOat.addItemListener(this::cbxSusuOatItemStateChanged);
        cbxSusuOat.addActionListener(this::cbxSusuOatActionPerformed);

        cbxExtraShot.setText("Extra Shot(+ Rp 4.000)");
        cbxExtraShot.addItemListener(this::cbxExtraShotItemStateChanged);
        cbxExtraShot.addActionListener(this::cbxExtraShotActionPerformed);

        lblTotalHargaText.setText("Total:");

        lblTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalHarga.setText("Rp25.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHargaLatte)
                    .addComponent(lblTambahan)
                    .addComponent(cbxGulaAren)
                    .addComponent(cbxSusuOat)
                    .addComponent(cbxExtraShot)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalHargaText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalHarga)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHargaLatte)
                .addGap(18, 18, 18)
                .addComponent(lblTambahan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxGulaAren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxSusuOat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxExtraShot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalHargaText)
                    .addComponent(lblTotalHarga))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxGulaArenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGulaArenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGulaArenActionPerformed

    private void cbxSusuOatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSusuOatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSusuOatActionPerformed

    private void cbxExtraShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxExtraShotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxExtraShotActionPerformed

    private void cbxGulaArenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxGulaArenItemStateChanged
        hitungTotal();
    }//GEN-LAST:event_cbxGulaArenItemStateChanged

    private void cbxSusuOatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSusuOatItemStateChanged
        hitungTotal();
    }//GEN-LAST:event_cbxSusuOatItemStateChanged

    private void cbxExtraShotItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxExtraShotItemStateChanged
        hitungTotal();
    }//GEN-LAST:event_cbxExtraShotItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CheckBoxTambahan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxExtraShot;
    private javax.swing.JCheckBox cbxGulaAren;
    private javax.swing.JCheckBox cbxSusuOat;
    private javax.swing.JLabel lblHargaLatte;
    private javax.swing.JLabel lblTambahan;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lblTotalHargaText;
    // End of variables declaration//GEN-END:variables
}
