/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.container;

/**
 *
 * @author bapti
 */
public class FramePesanDialog extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePesanDialog.class.getName());

    /**
     * Creates new form FramePesanDialog
     */
    public FramePesanDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogKonfirmasi = new javax.swing.JDialog();
        textKonfirmasi = new javax.swing.JLabel();
        btnKonfirmasi = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();

        dialogKonfirmasi.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogKonfirmasi.setTitle("dialogkonfirmasi");
        dialogKonfirmasi.setAlwaysOnTop(true);
        dialogKonfirmasi.setModal(true);

        textKonfirmasi.setText("Pesanan Anda Sudah Diterima. Terima Kasih");

        btnKonfirmasi.setText("Okay");
        btnKonfirmasi.addActionListener(this::btnKonfirmasiActionPerformed);

        javax.swing.GroupLayout dialogKonfirmasiLayout = new javax.swing.GroupLayout(dialogKonfirmasi.getContentPane());
        dialogKonfirmasi.getContentPane().setLayout(dialogKonfirmasiLayout);
        dialogKonfirmasiLayout.setHorizontalGroup(
            dialogKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogKonfirmasiLayout.createSequentialGroup()
                .addGroup(dialogKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogKonfirmasiLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(textKonfirmasi))
                    .addGroup(dialogKonfirmasiLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnKonfirmasi)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        dialogKonfirmasiLayout.setVerticalGroup(
            dialogKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogKonfirmasiLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(textKonfirmasi)
                .addGap(18, 18, 18)
                .addComponent(btnKonfirmasi)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblMenu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMenu.setText("Americano - Rp20.000");

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(this::btnPesanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnPesan)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblMenu)
                .addGap(18, 18, 18)
                .addComponent(btnPesan)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
       dialogKonfirmasi.pack();
       dialogKonfirmasi.setLocationRelativeTo(this);
       dialogKonfirmasi.setVisible(true);
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        dialogKonfirmasi.dispose();
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePesanDialog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JButton btnPesan;
    private javax.swing.JDialog dialogKonfirmasi;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel textKonfirmasi;
    // End of variables declaration//GEN-END:variables
}
